### ISSUE TITLE
adopt swiftx c7 and s4

### ISSUE THREAD

**Issue by noppoMan** [noppoMan/Slimane#12]
## 1st Stage

Preparing for adopting C4 and S7, Updating Zewo's HTTPParser, HTTP Packages and just run.
The  4.21 presentation will be done with this version.
### Details
- Swift3 Support
- SlimaneHTTPServer with recent Zewo's Packages, C4 and S7(But still incomplete compatibility)
- Router, Middlewares that has incomplete compatibility with C4 and S7
## 2nd Stage

For towarding the 90% C4 and S7 Compatibility.
### Details
- Confirming C4 and S7 for Suv(The Project is [SuvX](https://github.com/noppoMan/SuvX))
- SuvX based SlimaneHTTPServer/Client
- Improve compatibility with C4 and S7 for all of the Slimane related projects

**Comment by paulofaria** [comment]
Hey! Awesome that you're considering adopting `SwiftX`. Join [slack.swiftx.io](slack.swiftx.io) so we can discuss any issues that might arise. (:

**Comment by noppoMan** [comment]
@paulofaria 
Thanks for your inviting! Now I joined SwiftX slack.
Anyways, Zewo has been much helping me to do server side swift. It's a great project!
