### ISSUE TITLE
Actor modelで、Reactive manifest宣言対応のフレームワークにして欲しい

### ISSUE THREAD

**Issue by applideveloper** [noppoMan/Slimane#38]
https://github.com/ericholiveira/studio
Studio is a lightweight framework for node development to make easy to create reactive applications according to reactive manifesto principles. It uses micro-services (freely inspired by akka/erlang actors) implemented using bluebird a+ promises (or generators async/await) to solve the callback hell problem.
We all want our systems to be responsive, scalable, fault tolerant, maintainable and for the last, but not least, easy and fun to develop. With this goals in mind i decided to build a micro-services framework for nodejs using and architecture freely inspired on actors model. I present you Studio

**Comment by noppoMan** [comment]
@applideveloper 
これ、別レポジトリで実装考えましょうかw

**Comment by applideveloper** [comment]
すみません、クローズします。

**Comment by noppoMan** [comment]
@applideveloper 
actorモデル実装ってやったことありますか？
僕自身、swift-akka的なものを作りたい意欲はありまして

**Comment by applideveloper** [comment]
やったことないですけど、actor modelをC++で実装したものがあるので、Swiftで、ラップして使えたりするんですかね？
https://github.com/actor-framework/actor-framework
http://www.slideshare.net/TakamasaMitsuji/ss-13626473
http://www.slideshare.net/sifue/akka-39611889
Scalaの勉強会で、AkkaのActor model勉強してるのですが、Swiftでもできたら、嬉しいですね
http://ddd-cqrs-es.connpass.com/event/32311/
http://readeffectiveakka.connpass.com/event/32835/
http://reactive-programming-with-scala-and-akka.connpass.com/event/31710/
